### ISSUE TITLE
Some references to `std.os` don't exist anymore

### ISSUE THREAD

**Issue by manveru** [lun-4/zigdig#11]
Just stumbled over this:

https://github.com/lun-4/zigdig/blob/6d872bb061a85e416304b379ce3f3b868d6e835c/src/helpers.zig#L251-L252

should probably be:

```zig
    const flags: u32 = std.os.SOCK.DGRAM;
    const fd = try std.os.socket(addr.any.family, flags, std.os.IPPROTO.UDP);
```

It was easy enough to extract and fix the function, so it's nothing urgent, but wanted to let you know.

**Comment by lun-4** [comment]
...huh? I am not seeing the issue, those snippets are the exact same

**Comment by lun-4** [comment]
did a double take on the code and yes, there is an issue but it is not what you described, `std.os` should be `std.posix`, `connectToSystemResolver` does not use `connectToResolver` internally, so compiling the code didn't catch that

**Comment by lun-4** [comment]
closed by https://github.com/lun-4/zigdig/commit/1e615af5ee02fe437fb9fc3a1baa83fd239bd893

**Comment by manveru** [comment]
Sorry, you're right, I somehow pasted the wrong code here. Glad you figured it out anyway, and thanks for the fix :)
