### ISSUE TITLE
not an issue, but discussion.

### ISSUE THREAD

**Issue by binarycraft007** [lun-4/zigdig#7]
Hi @lun-4,  thanks for your great library, I made a async dns resolver with my libev zig wrapper, zero allocation except for the address list, really great!

Any suggestion would be welcome:
- testing code: https://github.com/binarycraft007/libev/blob/main/test/resolver.zig
- library: https://github.com/binarycraft007/libev/blob/main/src/ev/Resolver.zig

**Comment by lun-4** [comment]
that is very cool! I didn't write anything with intended async support as zig async is on its early steps, but I'm glad integration with libev is possible
